name: Test

on: [pull_request]

jobs:
  compile-and-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: sudo apt-get install -y clang-tidy
      - run: g++ test.cpp
      - run: git diff -U0 HEAD^ | clang-tidy-diff -checks="bugprone-*,readability-*,portability-*,performance-*,modernize-*,clang-analyzer-*,misc-*,-modernize-use-trailing-return-type,-readability-braces-around-statements" -p1 -export-fixes report.yml
      - uses: platisd/clang-tidy-pr-comments@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: report.yml
